# ||| ---------------------------- |||
# ||| hyprland  ------------------ |||
# ||| https://wiki.hypr.land  ---- |||
# ||| ---------------------------- |||

# monitors
source = ~/.config/hypr/modules/monitors.conf

# autostart
source = ~/.config/hypr/modules/autostart.conf

# environment variables
source = ~/.config/hypr/modules/envars.conf

# permissions
source = ~/.config/hypr/modules/permissions.conf

# looks
source = ~/.config/hypr/modules/looks.conf

# animations
source = ~/.config/hypr/modules/animations.conf

# layout
source = ~/.config/hypr/modules/layout.conf

# miscelleneous
source = ~/.config/hypr/modules/misc.conf

# input
source = ~/.config/hypr/modules/input.conf

# keybinds
source = ~/.config/hypr/modules/keybinds.conf

# window & workspace rules
source = ~/.config/hypr/modules/rules.conf
