# ||| -------------------------------------------------------------- |||
# ||| environment variables  --------------------------------------- |||
# ||| https://wiki.hypr.land/Configuring/Environment-variables  ---- |||
# ||| -------------------------------------------------------------- |||

env = __GLX_VENDOR_LIBRARY_NAME, nvidia
env = GBM_BACKEND, nvidia-drm
env = LIBVA_DRIVER_NAME, nvidia

env = XDG_CURRENT_DESKTOP, Hyprland
env = XDG_SESSION_TYPE, wayland
env = XDG_SESSION_DESKTOP, Hyprland

env = GDK_BACKEND, wayland, x11, *
env = QT_QPA_PLATFORM, wayland;xcb
env = QT_AUTO_SCREEN_SCALE_FACTOR, 1
env = SDL_VIDEODRIVER, wayland
env = CLUTTER_BACKEND, wayland

env = XCURSOR_THEME, catppuccin-mocha-lavender-cursors
env = HYPRCURSOR_THEME, catppuccin-mocha-lavender-cursors
env = XCURSOR_SIZE, 24
env = HYPRCURSOR_SIZE, 24

env = AWWW_TRANSITION, random
env = AWWW_TRANSITION_FPS, 144
env = AWWW_TRANSITION_STEP, 60
env = AWWW_TRANSITION_DURATION, 2
