# ||| ------------------------------------------------------- |||
# ||| layout  ----------------------------------------------- |||
# ||| https://wiki.hypr.land/Configuring/Dwindle-Layout  ---- |||
# ||| https://wiki.hypr.land/Configuring/Master-Layout  ----- |||
# ||| ------------------------------------------------------- |||

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}
