# ||| -------------------------------------------------------- |||
# ||| miscelleneous  ----------------------------------------- |||
# ||| https://wiki.hypr.land/Configuring/Variables/#misc  ---- |||
# ||| -------------------------------------------------------- |||

misc {
    disable_hyprland_logo = true
    force_default_wallpaper = 0
    vrr = 1
}
