# ||| -------------------------------------------------------- |||
# ||| window & workspace rules  ------------------------------ |||
# ||| https://wiki.hypr.land/Configuring/Window-Rules  ------- |||
# ||| https://wiki.hypr.land/Configuring/Workspace-Rules  ---- |||
# ||| -------------------------------------------------------- |||

windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}
